apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: operator-workload-placement-policy
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
