# permissions for end users to edit workloadplacementpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-workload-placement-policy
    app.kubernetes.io/managed-by: kustomize
  name: workloadplacementpolicy-editor-role
rules:
- apiGroups:
  - greenops.greenops.test
  resources:
  - workloadplacementpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greenops.greenops.test
  resources:
  - workloadplacementpolicies/status
  verbs:
  - get
